MOMAPP/Client/ClientApp/Models/AccountViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace ClientApp.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

MOMAPP/Client/ClientApp/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace ClientApp.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }
    }
}

MOMAPP/Client/ClientApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientApp.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddUser()
        {
            return View();
        }

        public ActionResult AddProject()
        {
            return View();
        }
	}
}

MOMAPP/Client/ClientApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientApp.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/
        public ActionResult Login()
        {
            return View();
        }
	}
}

MOMAPP/Client/ClientApp/Controllers/MomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace ClientApp.Controllers
{
    public class MomController : Controller
    {
        //
        // GET: /Mom/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateDoc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateDoc(FormCollection collection)
        {
            var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress("seemufassil@gmail.com"));  // replace with valid value 
            message.From = new MailAddress("mufassilsk@gmail.com");  // replace with valid value
            message.Subject = collection.Get("Subject");
            message.Body = collection.Get("Body");
            message.IsBodyHtml = true;

            using (var smtp = new SmtpClient())
            {
                var credential = new NetworkCredential
                {
                    UserName = "mufassilsk@gmail.com",  // replace with valid value
                    Password = "password"  // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = "smtp-mail.outlook.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.SendMailAsync(message);
                //return RedirectToAction("Sent");
                return View();
            }
        }
        public ActionResult History()
        {
            return View();
        }
    }
}

MOMAPP/Client/ClientApp/Views/Admin/AddProject.cshtml

@{
    ViewBag.Title = "AddProject";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}





<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Scripts/Admin/AddProject.js"></script>


</head>
<body>
    <form id="form1">
        <div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 well well-sm">

                <div class="row">

                    <div style="width:30%;margin-left:350px">
                        <br />
                        <br />

                        <h3 style="text-align:center">ADD USER</h3></br>
                        <label for=""> Project Name</label>
                        <input name="ProjectName" id="txtaddEmpName" placeholder="Project Name" type="text" class="form-control" style="width:300px" />
                        
                        <label for="comment" id="Subject">Start Date</label>
                        <input type="text" id="datepicker" class="form-control" style="width:300px" placeholder="Start Date"> 

                        <label for=""> Status</label>
                        <select id="ddlStatus" class="form-control" style="width:150px" >
                            <option style="display:none;">Select</option>
                            <option value="True">Active</option>
                            <option value="False">Completed</option>
                        </select>
                        <br/>

                        
                        <div align="center">
                            <input type="submit" value=" Save " class="btn btn-info" id="btnSave" style="width:100px" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    
</body>
</html>













MOMAPP/Client/ClientApp/Views/Admin/AddUser.cshtml

@{
    ViewBag.Title = "AddUser";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head >
    <title></title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Admin/AddUser.js"></script>
</head>
<body>

    <form id="form1">
        <div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 well well-sm">

                <div class="row" >
                   
                    <div  style="width:30%;margin-left:350px">
                        <br />
                        <br />

                        <h3 style="text-align:center">ADD USER</h3></br>
                        <label for=""> UserName</label>
                        <input class="form-control" name="UserName" id="uname" placeholder="UserName" type="text" /> <br />
                        <label for=""> Password</label>
                        <input class="form-control" name="Password" id="pwd" placeholder="Password" type="password" /> <br />
                        <label for=""> EmailID</label>
                        <input class="form-control" name="EmailId" id="email" placeholder="EmailId" type="text" /> <br />

                        <label for=""> Project</label>
                        <select class="form-control" id="ddlProject" style="width:50%"></select>

                        <label for=""> Role</label>
                        <select class="form-control" id="ddlRole" style="width:50%"></select>
                        <br />
                        <div align="center">
                            <input type="submit" value=" Save " class="btn btn-info" id="btnSave" style="width:100px" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>




MOMAPP/Client/ClientApp/Views/Admin/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h1>Welcome To Admin Page <small>Welcome To Admin Page</small></h1> 

<body></body>

MOMAPP/Client/ClientApp/Views/Login/Login.cshtml

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}

    @*Scripting Tags*@
    <title></title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
   @* <script src="~/Scripts/OurScripts/Login.js"></script>*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Login/Login.js"></script>



    @*Code for Designig*@

    <nav class="navbar navbar-inverse" style="width:1170px">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"></a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </div>
    </div>
    </nav>
    <div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Sign In</div>
                    <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                </div>

                <div style="padding-top:30px" class="panel-body">

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                    <form id="loginform" class="form-horizontal" role="form">

                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">
                        </div>

                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                        </div>



                        <div class="input-group">
                            <div class="checkbox">
                                <label>
                                    <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                </label>
                            </div>
                        </div>


                        <div style="margin-top:10px" class="form-group">
                            <!-- Button -->

                            <div align="center">
                                <a id="btn-login" class="btn btn-info" style="width:100px">Login  </a>
                                @*<input type="submit" value="Sign In" onclick="SignIN()" class="btn btn-success" />*@
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

MOMAPP/Client/ClientApp/Views/Mom/CreateDoc.cshtml
@{
    ViewBag.Title = "CreateDoc";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head >
    <title></title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <link href="~/Scripts/OurScripts/editor.css" rel="stylesheet" />
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/OurScripts/editor.js"></script>
    <script src="~/Scripts/Mom/CreateMom.js"></script>


    

</head>
<body>
  @*@using (Html.BeginForm("CreateDoc", "Mom", FormMethod.Post))*@
  
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 well well-sm">
          <div class="row">
              <div class="col-lg-8">
                  <div align="center">
                      <label for="comment">Select Project:</label>
                      <select id="ddlProject" class="form-control" style="width:150px"></select>
                  </div><br />
                  <label for="comment"  >Date:</label></br>
                  <input type="text" id="datepicker" class="form-control" style="width:250px"><br />
                  <label for="comment" >Subject:</label></br>
                  <input class="form-control" name="UserName" id="subject" type="text" />
                  <label for="comment" id="Body">Description:</label></br>
                  <textarea class="form-control" rows="5" id="messageBody"></textarea>
              </div>

              <div class="col-lg-4" style="text-align:center" id="divresult">
                  @*<label for="comment">Employee List:</label></br>*@
                  <br /><br /><br /><br />
                  <label for="comment">Employee List:</label></br>
                  <select name="List" id="List" multiple="multiple" class="form-control"></select>
                  <table id="tbl"></table>
              </div>
          </div><br/>
          <div style="text-align:center">
              <input type="submit" id="btn" class="btn btn-info" value="Save" style="width:100px">
          </div>
        </div>
            
        
  
</body>
</html>



MOMAPP/Client/ClientApp/Views/Mom/History.cshtml
@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/OurScripts/editor.css" rel="stylesheet" />
    <script src="~/Scripts/OurScripts/editor.js"></script>
    <script src="~/Scripts/Mom/History.js"></script>

</head>
<body>
    @*@using (Html.BeginForm("CreateDoc", "Mom", FormMethod.Post))*@

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 well well-sm">
        <div class="row">
            <div class="col-lg-8">
                <div >
                <table align="center">
                    <tr>
                        <td><label for="comment" >Select Project</label></td>
                        <td style="width:20px;text-align:center"><b>:</b></td>
                        <td><select id="ddlProject" class="form-control" style="width:150px"></select></td>
                    </tr>
                    <tr>
                        <td><label for="comment" id="Subject">Select Date: </label></td>
                        <td style="width:20px;text-align:center"><b>:</b></td>
                        <td><input type="text" id="datepicker" class="form-control" style="width:250px"></td>
                    </tr>
                </table>
                    
                </div><br />
                <div style="text-align:center">
                    <input type="submit" id="btnSearch" class="btn btn-info" value="Search" style="width:100px">
                </div>
            </div>
      </div>
   </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 well well-sm" id="divMom">
                    <div class="row">
                        <div class="col-lg-8">
                            <label for="comment" >Subject:</label></br>
                            <input type="text" class="form-control" id="subject" />
                            <label for="comment" >Description:</label></br>
                            <textarea class="form-control" rows="5" id="Description"></textarea>
                        </div>

                        <div class="col-lg-4" style="text-align:center" id="divresult">
                            @*<label for="comment">Employee List:</label></br>*@
                            <br /><br />
                            <label for="comment">Employee List:</label></br>
                            <select name="List" id="List" multiple="multiple" class="form-control"></select>
                            <table id="tbl"></table>
                        </div>
                    </div><br />
                    
                </div>



</body>
</html>



MOMAPP/Client/ClientApp/Views/Mom/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h1>Welcome To User Page <small>Welcome To User Page</small></h1>

<body>
</body>

MOMAPP/Client/ClientApp/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/OurScripts/GlobalSheet.css" rel="stylesheet" />
</head>

<body>
    
    <div class="container">
        <div class="row">

            <img src="~/Images/Green_Header.jpg" class="img-responsive" id="imgHeader" />
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">WebSiteName</a>
                    </div>
                    <div>
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="http://localhost:58405/admin/AddUser">Add User</a></li>
                            <li><a href="http://localhost:58405/admin/AddProject">Add Project</a></li>
                            <li><a href="http://localhost:58405/User/CreateDoc">Create Memo</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="row" id="divbody">
            @RenderBody()
        </div>
        <div class="row">
            <img src="~/Images/curve-header.png" class="img-responsive" id="imgFooter" />
        </div>
    </div>

</body>
</html>

MOMAPP/Client/ClientApp/Views/Shared/MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/OurScripts/GlobalSheet.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    
    <script src="~/Scripts/Layout/MainLayout.js"></script>
</head>

<body>

    <div class="container">
        <div class="row">

            <img src="~/Images/Back(02).jpg" class="img-responsive" id="imgHeader" />
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#" id="userName">WebSiteName</a>
                    </div>
                    <div>
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li id="admin1"><a href="http://localhost:58405/admin/AddUser">Add User</a></li>
                            <li id="admin2"><a href="http://localhost:58405/admin/AddProject">Add Project</a></li>
                            <li><a href="http://localhost:58405/Mom/CreateDoc">Create Memo</a></li>
                            <li><a href="http://localhost:58405/Mom/History">Search Memo</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="row" id="divbody">
            @RenderBody()
        </div>
        <div class="row">
            <img src="~/Images/black_footer.png" class="img-responsive" id="imgFooter" />
        </div>
    </div>

</body>
</html>

MOMAPP/Client/ClientApp/Views/Shared/_AppLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="~/Scripts/OurScripts/GlobalSheet.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">

            <img src="~/Images/Back(02).jpg" class="img-responsive" id="imgHeader" />
        </div>
        <div class="row" id="divbody">
            @RenderBody()
        </div>
        <div class="row">
            <img src="~/Images/black_footer.png" class="img-responsive" id="imgFooter" />
        </div>
    </div>
    
</body>
</html>

MOMAPP/Client/ClientApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>